# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.TextField(default='some_tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default-image.png', upload_to='img'),
        ),
    ]
