# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.TextField(choices=[('A', 'Not relevant'), ('B', 'Review'), ('C', 'Maybe relevant'), ('D', 'Relevant'), ('E', 'Leading candidate')], default='B'),
        ),
    ]
