# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20180406_1319'),
    ]

    operations = [
        migrations.RenameField('post', 'text', 'img_source')
    ]