# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-08 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='polarity',
            field=models.IntegerField(choices=[(0, 'Против'), (1, 'За')], default=1),
        ),
    ]
