# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-19 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_auto_20190218_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='quote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='blog.Quote'),
            preserve_default=False,
        ),
    ]
