# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-19 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_poll_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.TextField(blank=True),
        ),
    ]
