# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-19 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20190219_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='post',
        ),
    ]
