# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-19 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_remove_poll_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='blog.Post'),
            preserve_default=False,
        ),
    ]
