# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-22 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_remove_poll_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic_profile',
            field=models.TextField(default=''),
        ),
    ]
