# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-13 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_post_topic_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tp_rating',
            field=models.TextField(default=''),
        ),
    ]
